
application:
    hello: "hello World"

spring:
    profiles:
        active: -dev
    datasource: 
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost/university
        username: tutor
        password: secret
    liquibase:
        contexts: dev, faker
